/* ============================================================================
 * INDUSTRY PAGES  (tier 2)
 * =======================
 * Eleven pages, one per Industries menu category. The segments inside each
 * sector are sections on these pages, the same way services are sections on
 * the tier-2 service pages and products on the tier-2 product pages.
 *
 * Everything you might want to reword or re-image is in this file. Change the
 * text between the quote marks and save — the site picks it up on its own.
 *
 * TWO RULES WORTH KEEPING
 *   1. Keep the slugs in `industryPaths` stable. The navigation menu and any
 *      link you have shared point at them.
 *   2. Keep each segment `id` in step with the menu in `site.js`. The menu
 *      links to `/<slug>#<id>`, and the page scrolls to that section.
 *
 * IMAGES — two sectors have no photography of their own yet and borrow a
 * related picture. They are marked NEEDS ARTWORK below. Drop a proper image
 * into `public/assets/industries/` and change the path when you have one.
 *
 * ICONS are Material Symbols names. A name that is not listed in the
 * `icon_names=` list in `index.html` renders as an empty box — add it there
 * first if you introduce a new one.
 * ========================================================================= */

export const industryPaths = {
  'enterprise-corporate': '/enterprise-corporate',
  'manufacturing-industrial': '/manufacturing-industrial',
  'retail-consumer': '/retail-consumer-goods',
  'logistics-supply-chain': '/logistics-supply-chain',
  'healthcare-life-sciences': '/healthcare-life-sciences',
  'real-estate-construction': '/real-estate-construction',
  'professional-services': '/professional-services',
  'government-public': '/government-public-sector',
  'energy-sustainability': '/energy-sustainability-esg',
  'education-research': '/education-research',
  'travel-hospitality': '/travel-hospitality',
};

/* Wording shared by all eleven pages. Change it once, it changes everywhere. */
export const industryDetail = {
  home: 'Home',
  industries: 'Industries',
  skipLink: 'Skip to content',
  explore: 'Explore the Sector',
  talk: 'Talk to an Industry Expert',
  overview: 'Overview',
  segmentsNav: 'Who We Serve',
  capabilitiesNav: 'What We Deliver',
  approachNav: 'Approach',
  overviewEyebrow: 'The operating context',
  segmentsEyebrow: 'Inside this sector',
  segmentsTitle: 'Organizations we work with.',
  segmentFocus: 'Where we typically help',
  discuss: 'Discuss this segment',
  capabilitiesEyebrow: 'Applied capability',
  capabilitiesTitle: 'What ITG delivers in this sector.',
  approachEyebrow: 'How we engage',
  approachTitle: 'Sector context first, technology second.',
  approachIntro:
    'Industry work goes wrong when a platform is dropped into an operating model it was never shaped around. Every engagement starts with the constraints your sector actually runs under.',
  steps: [
    { title: 'Understand', body: 'Learn the sector’s operating model, reporting obligations and the constraints your teams work within.' },
    { title: 'Map', body: 'Translate those constraints into platform requirements, integration points and success measures.' },
    { title: 'Deliver', body: 'Build and validate in stages against the standards your industry is held to.' },
    { title: 'Sustain', body: 'Support adoption and keep the platform aligned as regulation and operations move.' },
  ],
  relatedEyebrow: 'Explore more',
  relatedTitle: 'Discover the other sectors we serve.',
  relatedLink: 'Explore sector',
  allIndustries: 'View All Industries',
  contactEyebrow: 'Your next step',
  // Configure an email to enable sector enquiries. The fallback is a live page.
  contactEmail: '',
  contactFallback: { label: 'Start a Conversation', href: '/contact?topic=project' },
};

export const industryCategories = [
  {
    id: 'enterprise-corporate',
    name: 'Enterprise & Corporate',
    shortName: 'Enterprise & Corporate',
    icon: 'apartment',
    image: '/assets/industries/ind-enterprise.jpg',
    focus: 'center',
    headline: 'One group.',
    accent: 'Many moving parts.',
    description:
      'Enterprise platforms for large organizations, holding companies and corporate groups, where governance has to hold across entities without stalling the entities themselves.',
    tags: ['Group governance', 'Shared services', 'Consolidated reporting'],
    overviewTitle: 'Group control that local teams can still work with.',
    lead: 'The tension is always central control against local speed.',
    overviewBody:
      'Corporate groups rarely struggle for systems. They struggle because each entity has its own, and the group layer is reconstructed by hand every reporting cycle. We build the shared foundation — common master data, entity-level access, intercompany flows — so consolidation stops being a monthly project while local teams keep the autonomy they need.',
    outcomes: [
      { icon: 'account_tree', title: 'A single group view', body: 'Consolidated reporting drawn from source systems rather than rebuilt in spreadsheets.' },
      { icon: 'hub', title: 'Shared services that scale', body: 'Common processes centralized once, consumed by every entity.' },
      { icon: 'verified_user', title: 'Governance that holds', body: 'Access, approvals and audit trails defined at group level and enforced locally.' },
    ],
    capabilities: [
      { icon: 'layers', title: 'Enterprise ERP and business platforms', body: 'A common operational foundation across finance, procurement and operations.' },
      { icon: 'hub', title: 'Shared services and centralized operations', body: 'Standardized back-office processes serving every entity in the group.' },
      { icon: 'bar_chart', title: 'Data governance and executive reporting', body: 'Agreed definitions, clear ownership and consolidated performance reporting.' },
      { icon: 'route', title: 'Process standardization and automation', body: 'Common workflows and approvals applied consistently across the group.' },
    ],
    segments: [
      {
        id: 'large-enterprises',
        name: 'Large Enterprises',
        icon: 'domain',
        description: 'Enterprise-scale operations',
        body: 'Organizations large enough that no single team sees the whole picture. The work is usually integration and reporting: connecting systems that grew up separately and giving leadership a view they can act on.',
        focus: ['Core platform modernization', 'Cross-function integration', 'Executive and operational reporting'],
      },
      {
        id: 'holding-groups',
        name: 'Holding Companies & Groups',
        icon: 'account_tree',
        description: 'Group-level governance',
        body: 'Holding structures need visibility into businesses they do not run day to day. We build the reporting and governance layer that gives the centre oversight without imposing one operating model on every subsidiary.',
        focus: ['Group consolidation and reporting', 'Subsidiary oversight and controls', 'Intercompany transactions and reconciliation'],
      },
      {
        id: 'conglomerates',
        name: 'Conglomerates',
        icon: 'layers',
        description: 'Multi-sector enterprises',
        body: 'Businesses spanning unrelated sectors cannot run on one process model. The aim is a common data and governance spine with genuinely different operations hanging off it.',
        focus: ['Common master data across sectors', 'Sector-specific operational systems', 'Unified group performance reporting'],
      },
      {
        id: 'shared-services',
        name: 'Shared Services Centers',
        icon: 'hub',
        description: 'Centralized service hubs',
        body: 'Shared service centres live or die on process discipline and measurable service levels. We build the workflow, routing and reporting that lets a central team serve many businesses predictably.',
        focus: ['Service request and workflow automation', 'Service level measurement and reporting', 'Cost allocation and recharging'],
      },
      {
        id: 'multi-entity',
        name: 'Multi-Entity Organizations',
        icon: 'apartment',
        description: 'Complex entity structures',
        body: 'Multiple legal entities mean multiple sets of books, currencies and reporting obligations. The platform has to keep them separate where the law requires and together where management needs.',
        focus: ['Entity structures and segregated access', 'Multi-currency and statutory reporting', 'Consolidation and elimination rules'],
      },
    ],
    feature: {
      eyebrow: 'Where group programmes stall',
      title: 'Master data is the whole problem.',
      body: 'Every group consolidation difficulty traces back to the same place: the same customer, supplier or cost centre recorded differently in each entity. We settle master data ownership and matching rules before the reporting layer is built, because no amount of reporting tooling fixes it afterwards.',
      points: ['Master data ownership agreed per domain', 'Matching and deduplication rules defined', 'Consolidation built on a reconciled base'],
      image: '/assets/company/itg-building.jpg',
      imageAlt: 'Corporate headquarters of a multi-entity organization',
    },
    cta: {
      title: 'Running a group on disconnected systems?',
      body: 'Tell us how many entities you consolidate and where the reporting cycle slows down. That is usually the right starting point.',
      label: 'Discuss an Enterprise Engagement',
    },
  },
  {
    id: 'manufacturing-industrial',
    name: 'Manufacturing & Industrial',
    shortName: 'Manufacturing',
    icon: 'factory',
    image: '/assets/industries/ind-manufacturing.jpg',
    focus: 'center',
    headline: 'The floor and the system.',
    accent: 'Telling the same story.',
    description:
      'Digital platforms for production, traceability and smart factory operations, built to reconcile what the plan says with what the shop floor is actually doing.',
    tags: ['Production visibility', 'Traceability', 'Connected operations'],
    overviewTitle: 'Close the gap between the plan and the floor.',
    lead: 'Planning systems and production reality drift apart daily.',
    overviewBody:
      'In most plants the schedule lives in one system, actual output in another, and quality in a third — reconciled by someone at the end of a shift. We connect production equipment, material movements and operational reporting so the picture is current rather than retrospective, and so traceability holds when a customer or auditor asks.',
    outcomes: [
      { icon: 'factory', title: 'Current production visibility', body: 'Output, downtime and material consumption visible as they happen.' },
      { icon: 'account_tree', title: 'Traceability that holds up', body: 'Lot and batch history reconstructable from raw material to dispatch.' },
      { icon: 'trending_up', title: 'Planning that reflects capacity', body: 'Schedules built on real throughput rather than nominal rates.' },
    ],
    capabilities: [
      { icon: 'factory', title: 'Manufacturing operations platforms', body: 'Production planning, execution and reporting on one connected system.' },
      { icon: 'neurology', title: 'Industry 4.0 and smart factory systems', body: 'Equipment and sensor data integrated into operational decisions.' },
      { icon: 'local_shipping', title: 'Supply chain visibility and planning', body: 'Material requirements aligned with production commitments.' },
      { icon: 'bolt', title: 'Industrial automation and analytics', body: 'Process automation and performance analysis across the plant.' },
    ],
    segments: [
      {
        id: 'manufacturing-ops',
        name: 'Manufacturing Operations',
        icon: 'factory',
        description: 'End-to-end operations',
        body: 'General manufacturing environments where planning, materials, production and quality need to sit on one operational picture rather than four disconnected ones.',
        focus: ['Production planning and scheduling', 'Material requirements and inventory', 'Quality recording and non-conformance'],
      },
      {
        id: 'textile-apparel',
        name: 'Textile & Apparel Manufacturing',
        icon: 'shopping_bag',
        description: 'Textile and apparel operations',
        body: 'Textile and apparel production carries style, size and colour dimensions that generic manufacturing systems handle badly. Costing and material planning have to work at that granularity.',
        focus: ['Style, colour and size matrix handling', 'Material planning and fabric utilization', 'Order-level costing and margin visibility'],
      },
      {
        id: 'spinning-mills',
        name: 'Spinning Mills & Processing Units',
        icon: 'settings',
        description: 'Spinning and processing units',
        body: 'Continuous processing has its own economics — count changes, blend ratios and machine-level efficiency drive cost more than headcount does. Systems have to record at that level to be useful.',
        focus: ['Count, blend and process parameter tracking', 'Machine-level efficiency and downtime', 'Process costing and yield analysis'],
      },
      {
        id: 'industry-4-0-factories',
        name: 'Industry 4.0 & Smart Factories',
        icon: 'neurology',
        description: 'Connected factory systems',
        body: 'Connecting equipment is the straightforward part. The value comes from deciding which signals matter, what they trigger, and who acts — which is where we start.',
        focus: ['Equipment and sensor data integration', 'Condition monitoring and alerting', 'Predictive and preventive maintenance'],
      },
      {
        id: 'heavy-light',
        name: 'Heavy & Light Industrial Enterprises',
        icon: 'build',
        description: 'Industrial enterprises',
        body: 'Industrial businesses running mixed make-to-order and make-to-stock work, where the same platform has to serve engineering, production and after-sales service.',
        focus: ['Make-to-order and project manufacturing', 'Asset and maintenance management', 'After-sales service and spares'],
      },
    ],
    feature: {
      eyebrow: 'A practical constraint',
      title: 'Shop-floor data has to be easy to enter.',
      body: 'Systems fail on the floor when recording is slower than the work. Operators route around anything that costs them time, and the data goes stale within weeks. We design capture around the actual working conditions — gloves, noise, movement — before worrying about the reports it feeds.',
      points: ['Capture designed for floor conditions', 'Minimal keystrokes per transaction', 'Validation at entry, not in reporting'],
      image: '/assets/services/ind-manufacturing.jpg',
      imageAlt: 'Industrial production line with connected monitoring systems',
    },
    cta: {
      title: 'Planning and production out of step?',
      body: 'Describe your production environment and where the reporting gaps sit. We will look at what it takes to close them.',
      label: 'Discuss a Manufacturing Engagement',
    },
  },
  {
    id: 'retail-consumer',
    name: 'Retail & Consumer Goods',
    shortName: 'Retail & Consumer',
    icon: 'shopping_cart',
    image: '/assets/industries/ind-retail.jpg',
    focus: 'center',
    headline: 'One inventory.',
    accent: 'Every channel.',
    description:
      'Commerce, inventory and customer platforms for retail and consumer businesses selling across stores, marketplaces and direct channels.',
    tags: ['Omnichannel inventory', 'Customer data', 'Channel performance'],
    overviewTitle: 'The channel count went up. The stock did not.',
    lead: 'Most retail problems are inventory accuracy problems.',
    overviewBody:
      'Selling across stores, a website and two marketplaces only works if every channel reads the same stock position. We connect commerce, inventory and fulfilment so availability is accurate, oversells stop, and customer information from each channel lands somewhere your teams can actually use.',
    outcomes: [
      { icon: 'shopping_cart', title: 'Accurate availability', body: 'One stock position serving every channel, updated as orders land.' },
      { icon: 'groups', title: 'A usable customer record', body: 'Purchase and service history joined across channels rather than siloed.' },
      { icon: 'bar_chart', title: 'Channel-level performance', body: 'Margin and movement visible by channel, category and location.' },
    ],
    capabilities: [
      { icon: 'shopping_cart', title: 'Retail and omnichannel platforms', body: 'Store, online and marketplace operations on shared inventory and pricing.' },
      { icon: 'language', title: 'E-commerce and marketplace integration', body: 'Listings, orders and fulfilment connected to core systems.' },
      { icon: 'groups', title: 'Customer engagement and CRM', body: 'Customer records and service history joined across every channel.' },
      { icon: 'bar_chart', title: 'Sales and performance analytics', body: 'Movement, margin and category performance in one reporting layer.' },
    ],
    segments: [
      {
        id: 'omnichannel',
        name: 'Retail & Omni-Channel Businesses',
        icon: 'shopping_cart',
        description: 'Unified retail channels',
        body: 'Retailers running stores alongside digital channels, where the operational challenge is a single stock and pricing position that every channel can trust.',
        focus: ['Unified inventory and pricing', 'Click-and-collect and cross-channel fulfilment', 'Store and online performance reporting'],
      },
      {
        id: 'fmcg',
        name: 'Consumer Goods & FMCG',
        icon: 'shopping_bag',
        description: 'FMCG operations',
        body: 'Fast-moving goods businesses where volume, shelf life and trade promotion economics drive the system requirements more than the catalogue does.',
        focus: ['Demand planning and replenishment', 'Batch, expiry and shelf-life control', 'Trade promotion and margin analysis'],
      },
      {
        id: 'ecommerce',
        name: 'E-Commerce & Marketplaces',
        icon: 'language',
        description: 'Marketplace ecosystems',
        body: 'Digital-first sellers operating across their own storefront and third-party marketplaces, each with its own listing rules, fees and fulfilment expectations.',
        focus: ['Multi-marketplace listing and order sync', 'Fulfilment and returns workflows', 'Channel fee and profitability analysis'],
      },
      {
        id: 'brand-distributors',
        name: 'Brand Owners & Distributors',
        icon: 'campaign',
        description: 'Brand and distribution',
        body: 'Brands selling through distribution need visibility past their own invoice — into sell-through, stock held in the channel and territory performance.',
        focus: ['Distributor and territory management', 'Sell-through and channel stock visibility', 'Pricing, rebates and claims'],
      },
      {
        id: 'private-label',
        name: 'Private Label Manufacturers',
        icon: 'layers',
        description: 'Private label operations',
        body: 'Producing under someone else’s brand means many specifications, short runs and exacting compliance documentation per customer.',
        focus: ['Customer specification management', 'Short-run planning and costing', 'Compliance and certification records'],
      },
    ],
    feature: {
      eyebrow: 'The unglamorous fix',
      title: 'Fix stock accuracy before adding channels.',
      body: 'Adding a marketplace to an inventory position that is already wrong multiplies the problem rather than growing the business. We check counting discipline, receipt and return handling first. It is a duller conversation than a new channel, and it is what makes the new channel work.',
      points: ['Stock accuracy assessed before expansion', 'Receipt and return handling tightened', 'One position published to every channel'],
      image: '/assets/services/ind-retail.jpg',
      imageAlt: 'Retail operations coordinated across physical and digital channels',
    },
    cta: {
      title: 'Selling across more channels than you can track?',
      body: 'Tell us your channel mix and where availability goes wrong. We will start there.',
      label: 'Discuss a Retail Engagement',
    },
  },
  {
    id: 'logistics-supply-chain',
    name: 'Logistics, Supply Chain & Operations',
    shortName: 'Logistics & Supply Chain',
    icon: 'local_shipping',
    image: '/assets/industries/ind-logistics.jpg',
    focus: 'center',
    headline: 'Know where it is.',
    accent: 'And what it costs.',
    description:
      'Platforms for warehousing, transport and distribution operations, where visibility and cost per movement decide whether the network works.',
    tags: ['Network visibility', 'Cost per movement', 'Operational control'],
    overviewTitle: 'Visibility is only useful if it is current.',
    lead: 'A location updated once a day is a location you cannot act on.',
    overviewBody:
      'Logistics operations are judged on exceptions — the late load, the missing pallet, the delivery that failed twice. We build the tracking, scanning and alerting that surfaces those while they can still be fixed, and connect them to the cost data that shows which lanes and customers actually pay.',
    outcomes: [
      { icon: 'route', title: 'Exceptions surfaced early', body: 'Delays and failures flagged while there is still time to intervene.' },
      { icon: 'deployed_code', title: 'Accurate stock positions', body: 'Scanned movements keeping warehouse records current by location.' },
      { icon: 'bar_chart', title: 'Cost that can be attributed', body: 'Movement cost traceable to lane, customer and service level.' },
    ],
    capabilities: [
      { icon: 'deployed_code', title: 'Warehouse management and control', body: 'Receipt, putaway, picking and dispatch under scanned control.' },
      { icon: 'local_shipping', title: 'Transport and fleet operations', body: 'Planning, execution and tracking across owned and contracted fleet.' },
      { icon: 'hub', title: 'Network and distribution visibility', body: 'Movement status across sites, carriers and partners in one view.' },
      { icon: 'bar_chart', title: 'Operational cost analytics', body: 'Cost per movement analysed by lane, customer and service level.' },
    ],
    segments: [
      {
        id: 'warehousing',
        name: 'Logistics & Warehousing',
        icon: 'deployed_code',
        description: 'Warehouse operations',
        body: 'Warehouse operations where accuracy comes from scanned, enforced processes rather than from counting more often.',
        focus: ['Receipt, putaway and location control', 'Directed picking and dispatch', 'Cycle counting and stock accuracy'],
      },
      {
        id: 'transportation-fleet',
        name: 'Transportation & Fleet Operations',
        icon: 'local_shipping',
        description: 'Fleet operations',
        body: 'Fleet operators balancing utilization against service commitments, where vehicle cost and driver hours are the constraints that matter.',
        focus: ['Route and load planning', 'Vehicle utilization and maintenance', 'Driver scheduling and compliance'],
      },
      {
        id: 'distribution-fulfillment',
        name: 'Distribution & Fulfillment Centers',
        icon: 'hub',
        description: 'Distribution networks',
        body: 'Multi-site distribution where the question is which site serves which order, and how stock is balanced across the network.',
        focus: ['Network stock balancing', 'Order allocation and sourcing rules', 'Site-level throughput reporting'],
      },
      {
        id: 'last-mile',
        name: 'Last-Mile Delivery',
        icon: 'route',
        description: 'Last-mile logistics',
        body: 'Final delivery is where most cost and nearly all customer experience sit. Proof, failure handling and re-attempt logic matter more than the route optimizer.',
        focus: ['Delivery sequencing and tracking', 'Proof of delivery and exceptions', 'Failed delivery and re-attempt handling'],
      },
      {
        id: 'supply-chain-ops',
        name: 'Supply Chain Operations',
        icon: 'account_tree',
        description: 'Supply chain execution',
        body: 'End-to-end supply chain teams needing one view across suppliers, inbound movement, stock and outbound commitments.',
        focus: ['Supplier and inbound visibility', 'Demand and replenishment planning', 'End-to-end performance measurement'],
      },
    ],
    feature: {
      eyebrow: 'What makes it work',
      title: 'Scanning discipline beats better software.',
      body: 'Warehouse accuracy is a process outcome, not a licensing one. If movements can be completed without a scan, the record will drift no matter what system sits behind it. We design the process so the scan is the fastest way to do the job.',
      points: ['Movements enforced through scanning', 'Exceptions routed, not silently allowed', 'Accuracy measured continuously'],
      image: '/assets/services/ind-logistics.jpg',
      imageAlt: 'Distribution centre operations with scanned movement control',
    },
    cta: {
      title: 'Losing visibility across the network?',
      body: 'Tell us where shipments go dark and what it costs you. That is the practical place to begin.',
      label: 'Discuss a Logistics Engagement',
    },
  },
  {
    id: 'healthcare-life-sciences',
    name: 'Healthcare & Life Sciences',
    shortName: 'Healthcare',
    icon: 'health_and_safety',
    image: '/assets/industries/ind-healthcare.jpg',
    focus: 'center',
    headline: 'Secure by obligation.',
    accent: 'Usable by necessity.',
    description:
      'Compliant platforms for providers, health technology and life sciences organizations, where patient safety and data protection set the floor for every design decision.',
    tags: ['Patient data protection', 'Regulatory readiness', 'Clinical usability'],
    overviewTitle: 'Compliance and usability are not opposites.',
    lead: 'A control that slows clinicians down gets bypassed.',
    overviewBody:
      'Healthcare systems have to satisfy regulators and clinicians at once, and a design that serves only the first fails both — because staff route around it. We build access control, audit and consent into workflows that still fit the pace of clinical work, and document the controls so an audit is a retrieval exercise rather than a project.',
    outcomes: [
      { icon: 'lock', title: 'Protected patient information', body: 'Role-based access and encryption applied by design, not retrofitted.' },
      { icon: 'verified_user', title: 'Audit-ready records', body: 'Access and change history retrievable without a reconstruction exercise.' },
      { icon: 'route', title: 'Workflows clinicians accept', body: 'Controls designed to fit clinical pace rather than obstruct it.' },
    ],
    capabilities: [
      { icon: 'health_and_safety', title: 'Clinical and provider systems', body: 'Patient administration, scheduling and clinical record platforms.' },
      { icon: 'lock', title: 'Data protection and access control', body: 'Consent, role-based access and encryption across patient information.' },
      { icon: 'verified_user', title: 'Regulatory and audit readiness', body: 'Traceable records and documented controls for inspection.' },
      { icon: 'hub', title: 'Systems integration and interoperability', body: 'Clinical, administrative and supply systems exchanging data reliably.' },
    ],
    segments: [
      {
        id: 'hospitals',
        name: 'Hospitals & Healthcare Providers',
        icon: 'health_and_safety',
        description: 'Provider operations',
        body: 'Providers coordinating admissions, clinical records, staffing and supply, where systems have to be dependable around the clock.',
        focus: ['Patient administration and scheduling', 'Clinical record access and audit', 'Resource, roster and supply coordination'],
      },
      {
        id: 'clinics',
        name: 'Clinics & Medical Centers',
        icon: 'groups',
        description: 'Clinical operations',
        body: 'Smaller clinical settings needing the same compliance posture as a hospital without the administrative weight that comes with it.',
        focus: ['Appointment and patient flow', 'Records, consent and privacy controls', 'Billing and claims workflows'],
      },
      {
        id: 'healthtech',
        name: 'HealthTech Companies',
        icon: 'devices',
        description: 'Health technology',
        body: 'Technology businesses building into healthcare, where integration standards and evidence of data protection decide whether a product can be adopted at all.',
        focus: ['Interoperability and clinical integration', 'Security architecture and assurance', 'Scalable, compliant product platforms'],
      },
      {
        id: 'pharma',
        name: 'Pharmaceuticals & Life Sciences',
        icon: 'verified_user',
        description: 'Pharma and life sciences',
        body: 'Regulated production and distribution where batch traceability and validated processes are obligations rather than improvements.',
        focus: ['Batch traceability and serialization', 'Validated process documentation', 'Quality management and deviation handling'],
      },
      {
        id: 'medical-supply',
        name: 'Medical Supply & Distribution',
        icon: 'local_shipping',
        description: 'Medical supply chains',
        body: 'Supply operations where expiry, cold chain and recall readiness carry consequences well beyond inventory value.',
        focus: ['Expiry and lot control', 'Cold chain monitoring', 'Recall traceability and response'],
      },
    ],
    feature: {
      eyebrow: 'Designing for inspection',
      title: 'Build the evidence trail as you go.',
      body: 'Organizations that treat audit preparation as an event spend weeks reconstructing what happened. Systems that record access, change and approval as a by-product of normal work turn that into a query. The cost difference over a few years is substantial.',
      points: ['Access and change logged by default', 'Approvals captured in the workflow', 'Evidence retrievable on request'],
      image: '/assets/services/ind-healthcare.jpg',
      imageAlt: 'Clinical teams working with secure connected healthcare systems',
    },
    cta: {
      title: 'Carrying compliance risk in your systems?',
      body: 'Tell us what you are held to and where the current setup strains. We will assess it honestly.',
      label: 'Discuss a Healthcare Engagement',
    },
  },
  {
    id: 'real-estate-construction',
    name: 'Real Estate, Construction & Facilities',
    shortName: 'Real Estate & Construction',
    icon: 'construction',
    image: '/assets/industries/ind-realestate.jpg',
    focus: 'center',
    headline: 'Assets, projects, and',
    accent: 'the cost of both.',
    description:
      'Integrated platforms for developers, contractors and facilities operators, connecting project delivery with the assets those projects become.',
    tags: ['Project controls', 'Asset lifecycle', 'Cost visibility'],
    overviewTitle: 'The project ends. The asset does not.',
    lead: 'Handover is where most information is lost.',
    overviewBody:
      'Construction and property organizations run two different businesses: delivering projects and operating what they produce. The information gathered during delivery is exactly what facilities teams need afterwards, and it is usually discarded at handover. We connect the two so commissioning data becomes operating data.',
    outcomes: [
      { icon: 'bar_chart', title: 'Cost visible during delivery', body: 'Commitment and spend tracked against budget while decisions can still change it.' },
      { icon: 'deployed_code', title: 'Assets with a history', body: 'Commissioning information carried through into operations and maintenance.' },
      { icon: 'construction', title: 'Controlled project delivery', body: 'Variations, approvals and progress recorded against a single plan.' },
    ],
    capabilities: [
      { icon: 'construction', title: 'Project controls and delivery', body: 'Programme, cost and variation management across the project lifecycle.' },
      { icon: 'deployed_code', title: 'Asset and facilities management', body: 'Asset registers, maintenance planning and lifecycle records.' },
      { icon: 'account_balance', title: 'Property and portfolio operations', body: 'Tenancy, leasing and portfolio performance management.' },
      { icon: 'bar_chart', title: 'Cost and commitment reporting', body: 'Budget, commitment and actual cost visible in one place.' },
    ],
    segments: [
      {
        id: 'real-estate-dev',
        name: 'Real Estate Developers',
        icon: 'apartment',
        description: 'Development operations',
        body: 'Developers managing capital commitment across a pipeline of schemes, where cash flow and sales progress drive every decision.',
        focus: ['Development appraisal and cost planning', 'Sales and reservation pipelines', 'Cash flow and funding reporting'],
      },
      {
        id: 'facilities',
        name: 'Property & Facilities Management',
        icon: 'settings',
        description: 'Facilities operations',
        body: 'Operators responsible for buildings in use, where planned maintenance, reactive work and tenant obligations compete for the same resources.',
        focus: ['Planned and reactive maintenance', 'Tenant requests and service levels', 'Contractor and compliance management'],
      },
      {
        id: 'construction-controls',
        name: 'Construction & Project Controls',
        icon: 'construction',
        description: 'Project delivery',
        body: 'Contractors and project teams needing programme, cost and variation control tight enough to defend a final account.',
        focus: ['Programme and progress tracking', 'Variation and change control', 'Subcontractor and valuation management'],
      },
      {
        id: 'infrastructure',
        name: 'Infrastructure & Utilities',
        icon: 'power',
        description: 'Infrastructure operations',
        body: 'Long-lived infrastructure where maintenance planning, regulatory obligations and asset condition determine investment priorities.',
        focus: ['Asset condition and criticality', 'Regulatory and safety compliance', 'Long-range investment planning'],
      },
      {
        id: 'asset-intensive',
        name: 'Asset-Intensive Organizations',
        icon: 'deployed_code',
        description: 'Asset-heavy enterprises',
        body: 'Organizations whose balance sheet is mostly physical assets, where lifecycle cost and availability matter more than acquisition price.',
        focus: ['Asset register and lifecycle costing', 'Maintenance strategy and availability', 'Replacement and disposal planning'],
      },
    ],
    feature: {
      eyebrow: 'The handover problem',
      title: 'Commissioning data is operating data.',
      body: 'Asset registers, warranties, maintenance schedules and drawings all exist at practical completion. Capturing them in a structured form at that moment costs a fraction of reconstructing them two years later, which is what facilities teams usually end up doing.',
      points: ['Asset data captured at commissioning', 'Warranties and documents linked to assets', 'Maintenance schedules live from day one'],
      image: '/assets/industries/cta-industries.jpg',
      imageAlt: 'Construction and property development under way',
    },
    cta: {
      title: 'Projects and operations on separate systems?',
      body: 'Tell us what gets lost at handover. That gap is usually worth closing first.',
      label: 'Discuss a Property Engagement',
    },
  },
  {
    id: 'professional-services',
    name: 'Professional Services',
    shortName: 'Professional Services',
    icon: 'work',
    image: '/assets/industries/ind-professional.jpg',
    focus: 'center',
    headline: 'Time is the product.',
    accent: 'Track it properly.',
    description:
      'Structured systems for consulting, legal, financial and managed service firms, where utilization and recoverability decide the result.',
    tags: ['Utilization', 'Engagement margin', 'Client confidentiality'],
    overviewTitle: 'You cannot manage a margin you cannot see until month end.',
    lead: 'Recoverability is decided during the engagement, not after it.',
    overviewBody:
      'Professional firms lose margin quietly: unbilled time, scope that expanded without a variation, engagements that were never profitable from the second week. We build the time capture, engagement structure and reporting that make those visible early enough to act on, with the confidentiality controls the work requires.',
    outcomes: [
      { icon: 'bar_chart', title: 'Margin visible early', body: 'Engagement profitability tracked during delivery rather than after invoicing.' },
      { icon: 'groups', title: 'Utilization you can act on', body: 'Chargeable time and capacity visible by person, team and practice.' },
      { icon: 'lock', title: 'Confidentiality maintained', body: 'Client separation and access control enforced by the platform.' },
    ],
    capabilities: [
      { icon: 'route', title: 'Engagement and project management', body: 'Scope, resourcing and delivery tracked from proposal to close.' },
      { icon: 'bar_chart', title: 'Time, billing and recoverability', body: 'Time capture through to invoice, with write-off visibility.' },
      { icon: 'groups', title: 'Client and relationship management', body: 'Client records, pipeline and engagement history in one place.' },
      { icon: 'lock', title: 'Confidentiality and access control', body: 'Matter-level separation, conflict checks and audit trails.' },
    ],
    segments: [
      {
        id: 'consulting',
        name: 'Consulting Firms',
        icon: 'groups',
        description: 'Advisory operations',
        body: 'Advisory businesses where resourcing decisions and scope discipline determine whether an engagement makes money.',
        focus: ['Resource planning and utilization', 'Engagement scope and change control', 'Project profitability reporting'],
      },
      {
        id: 'financial-advisory',
        name: 'Financial Advisory',
        icon: 'account_balance',
        description: 'Financial advisory firms',
        body: 'Advisory firms operating under regulatory obligation, where client suitability records and reporting have to be complete and retrievable.',
        focus: ['Client onboarding and suitability records', 'Regulatory reporting and retention', 'Portfolio and performance reporting'],
      },
      {
        id: 'legal-compliance',
        name: 'Legal & Compliance Firms',
        icon: 'balance',
        description: 'Legal operations',
        body: 'Legal practices where matter management, conflict checking and privileged document handling are foundational requirements.',
        focus: ['Matter and document management', 'Conflict checking and confidentiality', 'Time recording and billing'],
      },
      {
        id: 'accounting-audit',
        name: 'Accounting & Audit Firms',
        icon: 'bar_chart',
        description: 'Accounting and audit',
        body: 'Firms managing cyclical workload peaks and strict working paper standards, where evidence and review trails must be complete.',
        focus: ['Engagement and working paper management', 'Review, approval and sign-off trails', 'Deadline and workload planning'],
      },
      {
        id: 'managed-services',
        name: 'IT & Managed Services Providers',
        icon: 'cloud',
        description: 'Managed services',
        body: 'Service providers delivering against contracted service levels, where ticket economics and contract profitability need to be visible per client.',
        focus: ['Service desk and ticket workflows', 'Service level measurement and reporting', 'Contract and per-client profitability'],
      },
    ],
    feature: {
      eyebrow: 'The habit that decides it',
      title: 'Time recorded weekly is time already lost.',
      body: 'Recoverability tracks almost exactly with how promptly time is recorded. Entries made days later are estimates, and estimates are written off. Making capture take seconds, on whatever device is to hand, does more for margin than any pricing exercise.',
      points: ['Capture in seconds, on any device', 'Unbilled time visible weekly', 'Write-offs attributed to a cause'],
      image: '/assets/company/meeting.jpg',
      imageAlt: 'Professional services team reviewing an engagement',
    },
    cta: {
      title: 'Margin leaking between engagements?',
      body: 'Tell us how time is captured today and where recoverability drops. That is usually where the answer is.',
      label: 'Discuss a Professional Services Engagement',
    },
  },
  {
    id: 'government-public',
    name: 'Government & Public Sector',
    shortName: 'Government & Public',
    icon: 'account_balance',
    image: '/assets/services/ind-government.jpg',
    focus: 'center',
    headline: 'Accountable by default.',
    accent: 'Accessible to everyone.',
    description:
      'Secure, transparent platforms for public institutions, built to the accessibility and record-keeping standards public service is held to.',
    tags: ['Transparency', 'Accessibility', 'Records and retention'],
    overviewTitle: 'Public systems answer to everyone.',
    lead: 'Accessibility and auditability are requirements, not enhancements.',
    overviewBody:
      'A public service platform has to work for every citizen who needs it, including those using assistive technology or an old device on a poor connection, and it has to leave a record that stands up to scrutiny years later. We design to those obligations from the start, because retrofitting either one is expensive and rarely complete.',
    outcomes: [
      { icon: 'language', title: 'Services people can actually use', body: 'Accessible, low-bandwidth interfaces tested against real conditions.' },
      { icon: 'verified_user', title: 'Decisions that can be reviewed', body: 'Records and rationale retained to the required standard.' },
      { icon: 'lock', title: 'Security proportionate to the data', body: 'Controls matched to the sensitivity of what is held.' },
    ],
    capabilities: [
      { icon: 'language', title: 'Citizen-facing digital services', body: 'Accessible service interfaces and application workflows.' },
      { icon: 'menu_book', title: 'Records management and retention', body: 'Structured records with defined retention and disposal.' },
      { icon: 'verified_user', title: 'Transparency and audit', body: 'Decision trails and reporting that withstand external scrutiny.' },
      { icon: 'lock', title: 'Security and data protection', body: 'Access control and protective monitoring for sensitive information.' },
    ],
    segments: [
      {
        id: 'government-authorities',
        name: 'Government Authorities',
        icon: 'account_balance',
        description: 'Government bodies',
        body: 'Authorities delivering services directly to the public, where process consistency and a complete decision record are non-negotiable.',
        focus: ['Citizen service workflows', 'Case management and decision records', 'Performance and transparency reporting'],
      },
      {
        id: 'public-enterprises',
        name: 'Public Sector Enterprises',
        icon: 'domain',
        description: 'State-owned enterprises',
        body: 'State-owned businesses operating commercially while reporting publicly, needing systems that satisfy both sets of expectations.',
        focus: ['Commercial operations platforms', 'Public accountability reporting', 'Procurement and contract governance'],
      },
      {
        id: 'municipalities',
        name: 'Municipalities & Smart Cities',
        icon: 'apartment',
        description: 'Smart city programs',
        body: 'Local government coordinating services, infrastructure and resident interaction across departments that rarely share systems.',
        focus: ['Resident request and service coordination', 'Infrastructure and asset data', 'Cross-department integration'],
      },
      {
        id: 'regulatory',
        name: 'Regulatory Bodies',
        icon: 'balance',
        description: 'Regulatory agencies',
        body: 'Regulators managing licensing, inspection and enforcement, where consistency between similar cases is itself a legal requirement.',
        focus: ['Licensing and registration workflows', 'Inspection scheduling and findings', 'Enforcement case management'],
      },
      {
        id: 'public-infrastructure',
        name: 'Public Infrastructure Organizations',
        icon: 'power',
        description: 'Infrastructure bodies',
        body: 'Bodies responsible for public infrastructure, balancing asset condition, safety obligations and constrained investment budgets.',
        focus: ['Asset condition and safety records', 'Maintenance and works programmes', 'Investment planning and reporting'],
      },
    ],
    feature: {
      eyebrow: 'Designed for the edge case',
      title: 'Accessibility is not a final checklist.',
      body: 'Public services are used by people on assistive technology, on old devices and on poor connections. Treated as a pre-launch audit it produces a list of defects nobody has budget to fix. Designed in from the first wireframe it costs very little and changes who can use the service.',
      points: ['Accessibility standards set at design stage', 'Tested with assistive technology', 'Performance verified on low bandwidth'],
      image: '/assets/industries/hero-industries.jpg',
      imageAlt: 'Public sector facilities and civic infrastructure',
    },
    cta: {
      title: 'Modernizing a public service?',
      body: 'Tell us the service, the obligations it carries and who has to be able to use it. We will work from there.',
      label: 'Discuss a Public Sector Engagement',
    },
  },
  {
    id: 'energy-sustainability',
    name: 'Energy, Sustainability & ESG',
    shortName: 'Energy & Sustainability',
    icon: 'eco',
    image: '/assets/industries/ind-sustainability.jpg',
    focus: 'center',
    headline: 'Report what you can',
    accent: 'actually evidence.',
    description:
      'Sustainability, ESG and energy platforms built on data you can trace back to a source, because disclosure now carries the same scrutiny as financial reporting.',
    tags: ['Traceable data', 'Disclosure readiness', 'Assurance support'],
    overviewTitle: 'Disclosure is an evidence problem.',
    lead: 'A number you cannot trace is a number you cannot publish.',
    overviewBody:
      'Sustainability reporting has moved from narrative to assured disclosure, and the constraint is no longer intent — it is provenance. We build the collection, calculation and record-keeping so each published figure has a documented source, method and owner, and so assurance is a review rather than an investigation.',
    outcomes: [
      { icon: 'account_tree', title: 'Every figure has a source', body: 'Collection and calculation documented from raw input to disclosure.' },
      { icon: 'verified_user', title: 'Assurance-ready records', body: 'Method, owner and evidence retained alongside the reported number.' },
      { icon: 'trending_up', title: 'Progress you can measure', body: 'Consistent methods over time, so trends mean something.' },
    ],
    capabilities: [
      { icon: 'eco', title: 'Sustainability and ESG data platforms', body: 'Structured collection of environmental and social performance data.' },
      { icon: 'verified_user', title: 'Disclosure and assurance readiness', body: 'Documented methods, evidence and audit trails for reported figures.' },
      { icon: 'account_tree', title: 'Product and value chain traceability', body: 'Product-level records and supply chain transparency.' },
      { icon: 'bar_chart', title: 'Performance monitoring and reporting', body: 'Consistent measurement against targets over time.' },
    ],
    segments: [
      {
        id: 'sustainability-driven',
        name: 'Sustainability-Driven Enterprises',
        icon: 'eco',
        description: 'Sustainability leaders',
        body: 'Organizations with sustainability commitments they intend to be measured against, needing the data infrastructure to support the claim.',
        focus: ['Emissions and resource data collection', 'Target setting and progress tracking', 'Public reporting and evidence'],
      },
      {
        id: 'esg-focused',
        name: 'ESG-Focused Organizations',
        icon: 'target',
        description: 'ESG-centric orgs',
        body: 'Businesses reporting across environmental, social and governance dimensions to investors and regulators with differing expectations.',
        focus: ['Multi-framework ESG reporting', 'Governance and policy records', 'Investor and regulatory disclosure'],
      },
      {
        id: 'energy-utilities',
        name: 'Energy & Utilities',
        icon: 'power',
        description: 'Energy and utilities',
        body: 'Energy and utility operators managing generation, distribution and consumption data under continuous regulatory obligation.',
        focus: ['Consumption and generation data', 'Network asset and outage records', 'Regulatory performance reporting'],
      },
      {
        id: 'circular-economy',
        name: 'Circular Economy Initiatives',
        icon: 'route',
        description: 'Circularity programs',
        body: 'Programmes designed around reuse and recovery, which depend on knowing what a product contains and where it went.',
        focus: ['Material composition records', 'Reuse, recovery and end-of-life tracking', 'Digital product passport readiness'],
      },
      {
        id: 'environmental-compliance',
        name: 'Environmental Compliance Bodies',
        icon: 'verified_user',
        description: 'Environmental compliance',
        body: 'Organizations monitoring and enforcing environmental obligations, needing consistent evidence across many reporting parties.',
        focus: ['Monitoring and submission workflows', 'Compliance assessment and findings', 'Consistent evidence standards'],
      },
    ],
    feature: {
      eyebrow: 'Before the framework',
      title: 'Decide what you can evidence today.',
      body: 'Most organizations start by choosing a reporting framework and then discover the underlying data does not exist. Starting from what is genuinely measurable, and being explicit about what is estimated, produces a defensible first disclosure and a clear plan for the rest.',
      points: ['Measurable data identified first', 'Estimates labelled as estimates', 'Collection gaps planned, not hidden'],
      image: '/assets/services/ind-sustainability.jpg',
      imageAlt: 'Renewable energy infrastructure and environmental monitoring',
    },
    cta: {
      title: 'Facing a disclosure deadline?',
      body: 'Tell us what you report against and where the data is thin. We will give you a realistic view of the work.',
      label: 'Discuss a Sustainability Engagement',
    },
  },
  {
    id: 'education-research',
    name: 'Education & Research',
    shortName: 'Education & Research',
    icon: 'school',
    // NEEDS ARTWORK — no education photography exists yet; this borrows a
    // collaboration image. Replace with a campus or teaching picture.
    image: '/assets/company/about-people.jpg',
    focus: 'center',
    headline: 'Built around the',
    accent: 'academic calendar.',
    description:
      'Digital systems for universities, research organizations and training providers, where the year has hard deadlines and everything arrives at once.',
    tags: ['Peak-load ready', 'Research integrity', 'Student experience'],
    overviewTitle: 'The load is not spread evenly, and it never will be.',
    lead: 'Enrolment week is the system requirement.',
    overviewBody:
      'Academic institutions run on a calendar that concentrates demand into a few intense periods. Sizing for the average produces systems that fail exactly when they matter. We design for the peak, and for the reality that students, researchers and administrators need very different things from the same platform.',
    outcomes: [
      { icon: 'trending_up', title: 'Holds at peak', body: 'Capacity planned for enrolment and results periods, not the average week.' },
      { icon: 'menu_book', title: 'Research records that hold', body: 'Data management and retention aligned with funder and integrity requirements.' },
      { icon: 'groups', title: 'A coherent student experience', body: 'One record across application, enrolment, study and support.' },
    ],
    capabilities: [
      { icon: 'school', title: 'Student lifecycle platforms', body: 'Application, enrolment, progression and graduation on one record.' },
      { icon: 'neurology', title: 'Research data management', body: 'Project, funding and research output records with retention controls.' },
      { icon: 'menu_book', title: 'Learning and content systems', body: 'Course delivery, assessment and learning resource management.' },
      { icon: 'bar_chart', title: 'Institutional reporting', body: 'Statutory returns and performance reporting from consistent data.' },
    ],
    segments: [
      {
        id: 'universities',
        name: 'Universities & Institutions',
        icon: 'school',
        description: 'Academic institutions',
        body: 'Degree-awarding institutions coordinating admissions, teaching, assessment and statutory reporting across many faculties with their own conventions.',
        focus: ['Admissions and enrolment at peak load', 'Assessment, progression and awards', 'Statutory and funding returns'],
      },
      {
        id: 'research-orgs',
        name: 'Research Organizations',
        icon: 'neurology',
        description: 'Research organizations',
        body: 'Research bodies managing projects, funding conditions and data retention obligations that often outlast the projects themselves.',
        focus: ['Project and grant management', 'Research data storage and retention', 'Output, ethics and integrity records'],
      },
      {
        id: 'training-skills',
        name: 'Training & Skill Development',
        icon: 'menu_book',
        description: 'Learning and development',
        body: 'Training providers running rolling cohorts and accredited programmes, where certification records must be verifiable long afterwards.',
        focus: ['Cohort scheduling and delivery', 'Assessment and certification records', 'Accreditation and compliance evidence'],
      },
    ],
    feature: {
      eyebrow: 'Sizing honestly',
      title: 'Design for enrolment week.',
      body: 'A platform that performs comfortably for eleven months and collapses during enrolment has failed, and that is the week everyone remembers. We establish the peak concurrency figure early and design and test against it rather than the annual average.',
      points: ['Peak concurrency established up front', 'Load tested against the real peak', 'Degradation planned, not improvised'],
      image: '/assets/company/people-careers.jpg',
      imageAlt: 'Students and researchers working in an academic environment',
    },
    cta: {
      title: 'Systems straining at the start of term?',
      body: 'Tell us where the year puts pressure on your platforms. That is the practical place to start.',
      label: 'Discuss an Education Engagement',
    },
  },
  {
    id: 'travel-hospitality',
    name: 'Travel & Hospitality Services',
    shortName: 'Travel & Hospitality',
    icon: 'flight',
    // NEEDS ARTWORK — no hospitality photography exists yet; this borrows the
    // skyline image. Replace with a hotel, venue or travel picture.
    image: '/assets/cta-skyline.jpg',
    focus: 'center',
    headline: 'The guest sees one stay.',
    accent: 'Make the systems agree.',
    description:
      'Operational platforms for hotels, travel operators and experience businesses, where the guest experiences one journey and the business runs six systems.',
    tags: ['Unified guest record', 'Operational efficiency', 'Seasonal demand'],
    overviewTitle: 'The guest does not know where your systems end.',
    lead: 'Every handoff between systems is visible to the customer.',
    overviewBody:
      'Booking, front desk, housekeeping, food service and billing are usually separate platforms, and every seam between them shows up as a guest repeating themselves or a charge that does not reconcile. We connect them around one guest and one stay, and design for demand that swings hard by season and by day of the week.',
    outcomes: [
      { icon: 'groups', title: 'One guest record', body: 'Preferences, history and charges joined across every touchpoint.' },
      { icon: 'route', title: 'Operations that keep pace', body: 'Housekeeping, service and maintenance coordinated in real time.' },
      { icon: 'trending_up', title: 'Demand handled deliberately', body: 'Capacity, pricing and staffing planned against seasonal swing.' },
    ],
    capabilities: [
      { icon: 'groups', title: 'Guest and booking platforms', body: 'Reservation, stay and guest history on a connected record.' },
      { icon: 'route', title: 'Operational coordination', body: 'Housekeeping, service, maintenance and staffing in one flow.' },
      { icon: 'bar_chart', title: 'Revenue and demand analytics', body: 'Occupancy, rate and channel performance analysis.' },
      { icon: 'hub', title: 'Channel and partner integration', body: 'Distribution channels and partner systems kept in step.' },
    ],
    segments: [
      {
        id: 'hotels',
        name: 'Hotels & Hospitality Groups',
        icon: 'apartment',
        description: 'Hospitality groups',
        body: 'Properties and groups where front-of-house, housekeeping and finance need to work from the same live picture of every room and every guest.',
        focus: ['Reservation and front desk operations', 'Housekeeping and maintenance coordination', 'Occupancy, rate and revenue reporting'],
      },
      {
        id: 'travel-operators',
        name: 'Travel & Tourism Operators',
        icon: 'flight',
        description: 'Travel operators',
        body: 'Operators assembling itineraries from many suppliers, where a change to one component has to ripple through the booking, the cost and the customer.',
        focus: ['Itinerary and supplier management', 'Booking changes and cancellations', 'Margin and supplier cost tracking'],
      },
      {
        id: 'events',
        name: 'Event & Experience Companies',
        icon: 'campaign',
        description: 'Events and experiences',
        body: 'Event and experience businesses working to fixed dates, where resourcing, ticketing and on-the-day operations all converge on one moment.',
        focus: ['Event planning and resource scheduling', 'Ticketing and attendee management', 'On-site operations and settlement'],
      },
    ],
    feature: {
      eyebrow: 'Where the seams show',
      title: 'Reconciliation is a guest experience issue.',
      body: 'When the restaurant system and the property system disagree, the guest finds out at checkout. Connecting charge capture to the stay record removes an entire category of complaint, and it shortens the close at the same time.',
      points: ['Charges captured against the stay', 'Systems reconciled continuously', 'Disputes resolvable at the desk'],
      image: '/assets/industries/hero-industries.jpg',
      imageAlt: 'Hospitality operations serving guests across a property',
    },
    cta: {
      title: 'Guest experience breaking at the seams?',
      body: 'Tell us which systems do not talk to each other and where guests notice. We will start there.',
      label: 'Discuss a Hospitality Engagement',
    },
  },
];

export const industryPages = industryCategories.map(category => ({
  ...category,
  href: industryPaths[category.id],
}));
